import type { ParsedCardRow } from "@/types/db"

/** Seeded once for every brand-new profile — just enough to click
 *  through and see how studying works, not a real curriculum. Fully
 *  the student's own deck: they can edit or delete it like any other.
 *
 *  Every field carries all three languages. Russian is the required
 *  base that everything falls back to, English and Ukrainian are the
 *  optional overlays — so a student running the app in Ukrainian meets
 *  Ukrainian text on their very first card instead of a Russian
 *  fallback (which is what they got while these rows had no _uk at all).
 *  The deck's own name has no Ukrainian column yet; see the note in
 *  cardTranslation.ts's deckName(). */
export const STARTER_DECK_NAME = "Первые слова"
export const STARTER_DECK_NAME_EN = "First words"

export const STARTER_DECK_CARDS: ParsedCardRow[] = [
  {
    word_de: "Hallo",
    translation_ru: "привет",
    translation_en: "hello",
    translation_uk: "привіт",
    group: "Приветствия",
    group_en: "Greetings",
    group_uk: "Привітання",
    tags: ["greeting"],
    description: "Неформальное приветствие",
    description_en: "Informal greeting",
    description_uk: "Неформальне привітання",
    example_de: "Hallo, wie geht's?",
    example_ru: "Привет, как дела?",
    example_en: "Hello, how are you?",
    example_uk: "Привіт, як справи?",
  },
  {
    word_de: "Tschüss",
    translation_ru: "пока",
    translation_en: "bye",
    translation_uk: "бувай",
    group: "Приветствия",
    group_en: "Greetings",
    group_uk: "Привітання",
    tags: ["greeting"],
    description: "Неформальное прощание",
    description_en: "Informal goodbye",
    description_uk: "Неформальне прощання",
    example_de: "Tschüss, bis morgen!",
    example_ru: "Пока, до завтра!",
    example_en: "Bye, see you tomorrow!",
    example_uk: "Бувай, до завтра!",
  },
  {
    word_de: "danke",
    translation_ru: "спасибо",
    translation_en: "thank you",
    translation_uk: "дякую",
    group: "Вежливые слова",
    group_en: "Polite words",
    group_uk: "Ввічливі слова",
    tags: [],
    description: "",
    description_en: "",
    description_uk: "",
    example_de: "Danke für deine Hilfe.",
    example_ru: "Спасибо за твою помощь.",
    example_en: "Thanks for your help.",
    example_uk: "Дякую за твою допомогу.",
  },
  {
    word_de: "bitte",
    translation_ru: "пожалуйста",
    translation_en: "please / you're welcome",
    translation_uk: "будь ласка / прошу",
    group: "Вежливые слова",
    group_en: "Polite words",
    group_uk: "Ввічливі слова",
    tags: [],
    description: "",
    description_en: "",
    description_uk: "",
    example_de: "Ein Kaffee, bitte.",
    example_ru: "Один кофе, пожалуйста.",
    example_en: "One coffee, please.",
    example_uk: "Одну каву, будь ласка.",
  },
  {
    word_de: "ja",
    translation_ru: "да",
    translation_en: "yes",
    translation_uk: "так",
    group: "Основы",
    group_en: "Basics",
    group_uk: "Основи",
    tags: [],
    description: "",
    description_en: "",
    description_uk: "",
    example_de: "Ja, das stimmt.",
    example_ru: "Да, это верно.",
    example_en: "Yes, that's right.",
    example_uk: "Так, це правильно.",
  },
  {
    word_de: "nein",
    translation_ru: "нет",
    translation_en: "no",
    translation_uk: "ні",
    group: "Основы",
    group_en: "Basics",
    group_uk: "Основи",
    tags: [],
    description: "",
    description_en: "",
    description_uk: "",
    example_de: "Nein, danke.",
    example_ru: "Нет, спасибо.",
    example_en: "No, thank you.",
    example_uk: "Ні, дякую.",
  },
  {
    word_de: "das Wasser",
    translation_ru: "вода",
    translation_en: "water",
    translation_uk: "вода",
    group: "Еда и напитки",
    group_en: "Food & drink",
    group_uk: "Їжа та напої",
    tags: ["noun"],
    description: "Сущ. ср. рода",
    description_en: "Neuter noun",
    description_uk: "Іменник середнього роду",
    example_de: "Ich trinke gern Wasser.",
    example_ru: "Я люблю пить воду.",
    example_en: "I like drinking water.",
    example_uk: "Я люблю пити воду.",
  },
  {
    word_de: "gut",
    translation_ru: "хорошо",
    translation_en: "good",
    translation_uk: "добре",
    group: "Основы",
    group_en: "Basics",
    group_uk: "Основи",
    tags: ["adjective"],
    description: "",
    description_en: "",
    description_uk: "",
    example_de: "Mir geht es gut.",
    example_ru: "У меня всё хорошо.",
    example_en: "I'm doing well.",
    example_uk: "У мене все добре.",
  },
]
