import type { ParsedCardRow } from "@/types/db"

/** Seeded once for every brand-new profile — just enough to click
 *  through and see how studying works, not a real curriculum. Fully
 *  the student's own deck: they can edit or delete it like any other. */
export const STARTER_DECK_NAME = "Первые слова"
export const STARTER_DECK_NAME_EN = "First words"

export const STARTER_DECK_CARDS: ParsedCardRow[] = [
  {
    word_de: "Hallo",
    translation_ru: "привет",
    translation_en: "hello",
    group: "Приветствия",
    group_en: "Greetings",
    tags: ["greeting"],
    description: "Неформальное приветствие",
    description_en: "Informal greeting",
    example_de: "Hallo, wie geht's?",
    example_ru: "Привет, как дела?",
    example_en: "Hello, how are you?",
  },
  {
    word_de: "Tschüss",
    translation_ru: "пока",
    translation_en: "bye",
    group: "Приветствия",
    group_en: "Greetings",
    tags: ["greeting"],
    description: "Неформальное прощание",
    description_en: "Informal goodbye",
    example_de: "Tschüss, bis morgen!",
    example_ru: "Пока, до завтра!",
    example_en: "Bye, see you tomorrow!",
  },
  {
    word_de: "danke",
    translation_ru: "спасибо",
    translation_en: "thank you",
    group: "Вежливые слова",
    group_en: "Polite words",
    tags: [],
    description: "",
    description_en: "",
    example_de: "Danke für deine Hilfe.",
    example_ru: "Спасибо за твою помощь.",
    example_en: "Thanks for your help.",
  },
  {
    word_de: "bitte",
    translation_ru: "пожалуйста",
    translation_en: "please / you're welcome",
    group: "Вежливые слова",
    group_en: "Polite words",
    tags: [],
    description: "",
    description_en: "",
    example_de: "Ein Kaffee, bitte.",
    example_ru: "Один кофе, пожалуйста.",
    example_en: "One coffee, please.",
  },
  {
    word_de: "ja",
    translation_ru: "да",
    translation_en: "yes",
    group: "Основы",
    group_en: "Basics",
    tags: [],
    description: "",
    description_en: "",
    example_de: "Ja, das stimmt.",
    example_ru: "Да, это верно.",
    example_en: "Yes, that's right.",
  },
  {
    word_de: "nein",
    translation_ru: "нет",
    translation_en: "no",
    group: "Основы",
    group_en: "Basics",
    tags: [],
    description: "",
    description_en: "",
    example_de: "Nein, danke.",
    example_ru: "Нет, спасибо.",
    example_en: "No, thank you.",
  },
  {
    word_de: "das Wasser",
    translation_ru: "вода",
    translation_en: "water",
    group: "Еда и напитки",
    group_en: "Food & drink",
    tags: ["noun"],
    description: "Сущ. ср. рода",
    description_en: "Neuter noun",
    example_de: "Ich trinke gern Wasser.",
    example_ru: "Я люблю пить воду.",
    example_en: "I like drinking water.",
  },
  {
    word_de: "gut",
    translation_ru: "хорошо",
    translation_en: "good",
    group: "Основы",
    group_en: "Basics",
    tags: ["adjective"],
    description: "",
    description_en: "",
    example_de: "Mir geht es gut.",
    example_ru: "У меня всё хорошо.",
    example_en: "I'm doing well.",
  },
]
